export const playgrounds = [
	{ value: 'pg1', label: '81 - Panthera' },
	{ value: 'pg2', label: '82 - Panthera' },
	{ value: 'pg3', label: '83 - Minions' },
	{ value: 'pg5', label: '89 - Minions' },
	{ value: 'pg7', label: '90 - Minions' },
	{ value: 'pg8', label: '91 - Minions' },
	{ value: 'pg9', label: '92 - Plan B' },
	{ value: 'pg10', label: '93 - Plan B (ZData bank testing)' },
	{ value: 'pg11', label: '94 - Team Cobrador' },
	{ value: 'pg12', label: '96 - Team Cobrador' },
	{ value: 'pg13', label: '97 - Panthera' },
	{ value: 'pg14', label: '98 - Panthera' },
	{ value: 'pg15', label: '99 - Lars-Martin' },
	{ value: 'pg16', label: '100 - Restack' },
	{ value: 'pg17', label: '170 - Restack' },
	{ value: 'pg18', label: '180 - Restack' },
	{ value: 'pg19', label: '190 - Minions' },
	{ value: 'pg20', label: '200 - Team Cobrador' },
	{ value: 'pg21', label: '210 - Team Cobrador' },
	{ value: 'pg22', label: '220 - Minions' },
	{ value: 'pg23', label: '230 - Stark' },
	{ value: 'pg24', label: '240 - Plan B' },
	{ value: 'pg25', label: '250 - Team Cobrador' },
	{ value: 'pg26', label: '260 - Team Cobrador' },
	{ value: 'pg27', label: '270 - Frontend testing' },
	{ value: 'pg28', label: '280 - Team Cobrador' },
	{ value: 'pg29', label: '290 - Minions' },
	{ value: 'pg30', label: '300 - Sveinung' },
	{ value: 'pg31', label: '310 - Daniel' },
	{ value: 'pg32', label: '320 - Sondreo' },
	{ value: 'pg33', label: '330 - Dennis' },
	{ value: 'pg34', label: '340 - Team Cobrador' },
	{ value: 'pg35', label: '350 - Frode' },
	{ value: 'pg36', label: '360 - Terje' },
	{ value: 'pg37', label: '370 - Team Cobrador' },
	{ value: 'pg38', label: '380 - Anders' },
	{ value: 'pg39', label: '390 - Minions' },
	{ value: 'pg40', label: '400 - Minions' },
	{ value: 'pg41', label: '410 - Jan Ove' },
	{ value: 'pg42', label: '420 - Azets' },
	{ value: 'pg43', label: '430 - Team Cobrador' },
	{ value: 'pg44', label: '440 - Team Cobrador' },
	{ value: 'pg45', label: '450 - Altinn / KarlC' },
	{ value: 'pg46', label: '460 - Team Cobrador' },
	{ value: 'pg47', label: '470 - Team Cobrador' },
	{ value: 'pg48', label: '480 - Team Cobrador' },
	{ value: 'pg49', label: '490 - Team Cobrador' },
	{ value: 'pg50', label: '500 - Team Cobrador' },
	{ value: 'pg51', label: '510 - Team Cobrador' },
	{ value: 'pg52', label: '520 - Frode / SB1' },
	{ value: 'pg53', label: '533 - Sparebanken Sør' },
	{ value: 'pg54', label: '541 - softrig-training' },
	{ value: 'pg55', label: '550 - landbruk' },
	{ value: 'pg56', label: '560 - landbruk' },
	{ value: 'pg57', label: '570 - Eika' },
	{ value: 'pg58', label: '580 - Minions' },
	{ value: 'pg59', label: '590 - Minions' }
];
